const jobs=[
{company:'Patient Square Capital',role:'Summer Intern',date:'Jun–Jul 2026',location:'Menlo Park, CA',theme:'Understanding the range of investment outcomes',metric:'10,000+',label:'Monte Carlo iterations across key assumptions',bullets:['Built LBO models for a portfolio company investment and identified the key drivers of return variance.','Adapted a proprietary Monte Carlo simulation framework to a new portfolio company. Ran 10,000+ iterations across key assumptions to generate probability distributions and cumulative distribution functions—a probabilistic alternative to traditional LBO models.','Researched the portfolio company’s business model, core return drivers, and investment thesis.','Presented business model analysis and probabilistic LBO methodology to the insights team and a partner.']},
{company:'Ring Therapeutics',role:'Summer Intern',date:'Jul–Aug 2025',location:'Cambridge, MA',theme:'Following biotechnology M&A and funding activity while gaining hands-on lab experience',metric:'Daily',label:'AI-powered news monitoring and HTML email digests',bullets:['Developed an AI agent workflow to filter, summarize, and deliver news tailored to customizable profiles, covering M&A, funding, regulatory shifts, and biotechnology.','Connected detailed results to Google Sheets to power automated daily HTML email digests.','Presented the workflow and results to the CEO and leadership team, with a detailed deployment guide for continued use.','Supported in vivo experiments and biotechnology lab operations, gaining exposure to advanced lab instrumentation.']},
{company:'Averin Capital',role:'Investment Research Intern',date:'Jun–Aug 2024',location:'New York, NY',theme:'Finding and evaluating healthcare investment opportunities',metric:'20+',label:'Healthcare startups screened and evaluated',bullets:['Analyzed employee growth, funding history, valuation metrics, and market traction to identify opportunities aligned with the firm’s investment thesis.','Delivered internal investment prospect reports in Excel that informed deal team discussions and negotiations.','Used PitchBook to source potential investments, conduct due diligence, and compile primary company contacts.']},
{company:'Corium',role:'Summer Intern',date:'Jul–Sep 2022',location:'Boston, MA',theme:'Connecting patient behavior to business decisions',metric:'Research → action',label:'Findings contributed to an advertising campaign',bullets:['Analyzed ADHD patient and caregiver behavior across social media to assess influences on prescription decisions.','Organized medication review data in Excel to identify sentiment trends and ratings across multiple ADHD drugs.','Presented findings to the CEO, leadership team, and marketing team, leading to the implementation of an advertising campaign.']}
];
const functions={OV:'Overview',EXP:'Professional experience',EDU:'Education',ACT:'Campus involvement',FPV:'FPV drones & personal interests',CONTACT:'Contact',HELP:'Function directory'};
const main=document.querySelector('main'),input=document.querySelector('#command'),suggestions=document.querySelector('#suggestions');let current='OV',selectedJob=0;
const panel=(title,body,code='',cls='')=>`<section class="panel ${cls}"><div class="panel-head"><strong>${title}</strong><span>${code}</span></div>${body}</section>`;
const heading=(code,title)=>`<div class="page-heading"><h1>${code} &lt;GO&gt; &nbsp; ${title}</h1><small>BRENDAN WILSON / PERSONAL PROFILE</small></div>`;
const experienceRows=()=>`<table class="rows"><thead><tr><th>Company / role</th><th>Period</th><th></th></tr></thead><tbody>${jobs.map((j,i)=>`<tr><td><button class="row-button" data-job="${i}">${j.company}<span>${j.role}</span></button></td><td class="date">${j.date}</td><td class="arrow">↗</td></tr>`).join('')}</tbody></table><button class="panel-link" data-view="EXP">EXP &lt;GO&gt; &nbsp; Explore professional experience →</button>`;
function overview(){return heading('OV','Overview')+`<div class="grid"><section class="panel intro"><div class="panel-head blue"><strong>Profile / Brendan Wilson</strong><span>BW US · PERSONAL</span></div><div class="panel-body"><div class="profile-heading"><img class="headshot" src="headshot.jpeg" alt="Brendan Wilson" width="64" height="64"><div><div class="eyebrow">FINANCE · HEALTHCARE</div><h2>Brendan Wilson</h2></div></div><p>I’m a finance student at <strong>The Ohio State University</strong> pursuing a career in <strong>investment banking</strong>. My experience spans healthcare investment analysis, hands-on biotechnology lab work, and pharmaceutical market research.</p><p>I’m interested in the businesses behind healthcare innovation and the financial decisions that shape their growth. Outside of work and school, I build <strong>FPV drones</strong>.</p><div class="tags"><span>Boston, MA</span><span>Ohio State ’29</span><span>Fisher College of Business</span></div><div class="metrics"><div class="metric"><b>3.94<span style="display:inline"> / 4.00</span></b><span>GPA</span></div><div class="metric"><b>4</b><span>Internship experiences</span></div></div></div></section>${panel('Experience monitor',experienceRows(),'EXP')}</div>
<div class="lower">
${panel('01 / Healthcare investment analysis',`<div class="panel-body"><div class="eyebrow">PATIENT SQUARE CAPITAL</div><h3>Modeling investment outcomes.</h3><p>Built LBO models, examined a portfolio company’s business model, and used Monte Carlo simulations to analyze the drivers of investment returns.</p><button data-job="0">View the experience →</button></div>`,'2026','mini')}
${panel('02 / Biotechnology',`<div class="panel-body"><div class="eyebrow">RING THERAPEUTICS</div><h3>From sector news to the lab.</h3><p>Built a daily AI news workflow tracking M&A activity, funding trends, and regulatory shifts. Also supported in vivo experiments and biotechnology lab operations.</p><button data-job="1">View the experience →</button></div>`,'2025','mini')}
${panel('03 / Healthcare investment research',`<div class="panel-body"><div class="eyebrow">AVERIN CAPITAL</div><h3>Evaluating emerging healthcare businesses.</h3><p>Screened 20+ healthcare startups using growth, funding, valuation, and market traction data. Prepared investment prospect reports to support deal team discussions.</p><button data-job="2">View the experience →</button></div>`,'2024','mini')}
${panel('04 / Pharmaceuticals',`<div class="panel-body"><div class="eyebrow">CORIUM</div><h3>Understanding patients and caregivers.</h3><p>Researched ADHD patient and caregiver behavior and medication reviews. Presented findings to leadership and marketing, contributing to an advertising campaign.</p><button data-job="3">View the experience →</button></div>`,'2022','mini')}
</div>
<div class="grid overview-section">
${panel('Education & academic programs',`<div class="panel-body"><div class="focus-item"><span class="index">01</span><div><h3>The Ohio State University</h3><p>BSBA, Finance · Expected May 2029<br>National Buckeye Scholarship · University Honors · Dean’s List</p></div></div><div class="focus-item"><span class="index">02</span><div><h3>Fisher Futures Investment Banking Program</h3><p>One of 32 students selected for training in investment banking, modeling, forecasting, and valuation.</p></div></div><div class="focus-item"><span class="index">03</span><div><h3>Business Scholars Program</h3><p>One of 83 students selected from 500+ applicants for a two-year program in business, networking, and mentorship.</p></div></div><div class="focus-item"><span class="index">04</span><div><h3>Certifications</h3><p>Artificial Intelligence Scholar — Inspirit AI<br>Qualified Undergraduate Interview Candidate — QUIC</p></div></div></div><button class="panel-link" data-view="EDU">EDU &lt;GO&gt; &nbsp; Education & academic programs →</button>`,'OSU')}
${panel('Campus involvement',`<div class="panel-body"><div class="focus-item"><span class="index">01</span><div><h3>Buckeye Capital Investors</h3><p>Healthcare Sector Analyst · February 2026–present<br>One of 20 selected from 150+ applicants; focused on fundamental analysis, portfolio management, and valuation.</p></div></div><div class="focus-item"><span class="index">02</span><div><h3>Buckeye Private Equity and Venture Capital Club</h3><p>Analyst · February 2026–present<br>One of 25 selected from 150+ applicants for a multidisciplinary, project-based PE and VC club.</p></div></div><div class="focus-item"><span class="index">03</span><div><h3>Investment Banking Pathway</h3><p>Member · February 2026–September 2026<br>Completed 15-week investment banking training and a sell-side advisory capstone on Intersnack’s acquisition of Utz, using DCF, comparable company, and precedent transactions analyses.</p></div></div></div><button class="panel-link" data-view="ACT">ACT &lt;GO&gt; &nbsp; Explore campus involvement →</button>`,'ACT')}
</div>
<div class="grid overview-section">${panel('Outside work & school',`<div class="panel-body"><div class="eyebrow">PERSONAL INTEREST</div><h3>Building FPV drones.</h3><p>Outside my interest in healthcare and finance, I enjoy building first-person-view drones.</p><button data-view="FPV">Open the flight deck →</button></div>`,'FPV','mini')}${panel('Quick functions',`<div class="function-list"><button data-view="EDU"><b>EDU</b><span>Education & academic programs ↗</span></button><button data-view="ACT"><b>ACT</b><span>Clubs & campus involvement ↗</span></button><button data-view="CONTACT"><b>CONTACT</b><span>Get in touch ↗</span></button><button data-view="HELP"><b>HELP</b><span>Browse all terminal functions ↗</span></button></div>`,'DIRECTORY')}</div>`}
function experience(){const j=jobs[selectedJob];return heading('EXP','Professional experience')+`<div class="detail-grid">${panel('Experience index',`<div class="side-menu">${jobs.map((x,i)=>`<button data-job="${i}" class="${selectedJob===i?'selected':''}">${x.company}<span>${x.date}</span></button>`).join('')}</div>`,'4')}${panel(j.company,`<article class="article"><div class="eyebrow">${j.date.toUpperCase()} · ${j.location.toUpperCase()}</div><h2>${j.company}</h2><div class="subtitle">${j.role}</div><p>${j.theme}.</p><div class="highlight"><strong>${j.metric}</strong><p>${j.label}</p></div><h3>WORK & CONTRIBUTIONS</h3><ul>${j.bullets.map(x=>`<li>${x}</li>`).join('')}</ul></article>`,'EXPERIENCE')}</div>`}
function education(){return heading('EDU','Education')+`<div class="grid">${panel('The Ohio State University',`<article class="article"><div class="eyebrow">MAX M. FISHER COLLEGE OF BUSINESS</div><h2>Building a foundation in finance.</h2><div class="subtitle">Bachelor of Science in Business Administration</div><dl class="facts"><dt>Specialization</dt><dd>Finance</dd><dt>Graduation</dt><dd>May 2029</dd><dt>Location</dt><dd>Columbus, OH</dd><dt>GPA</dt><dd class="green">3.94 / 4.00</dd></dl><h3>ACADEMIC RECOGNITION</h3><ul><li>National Buckeye Scholarship</li><li>University Honors</li><li>Dean’s List</li></ul></article>`,'OSU')}${panel('Selected programs & certifications',`<article class="article"><h3 style="margin-top:0">FISHER FUTURES INVESTMENT BANKING PROGRAM</h3><p>One of 32 students in a highly competitive, faculty-selected program covering investment banking, financial modeling, forecasting, and business valuation.</p><h3>BUSINESS SCHOLARS PROGRAM</h3><p>One of 83 students selected from 500+ applicants for a two-year program covering interview techniques, networking, mentorship, and trips.</p><h3>CERTIFICATIONS</h3><p>Artificial Intelligence Scholar — Inspirit AI<br>Qualified Undergraduate Interview Candidate — QUIC</p></article>`,'PROGRAMS')}</div>`}
function activities(){return heading('ACT','Campus involvement')+panel('Learning alongside a community',`<article class="article"><div class="eyebrow">THE OHIO STATE UNIVERSITY · COLUMBUS, OH</div><h2>Finance beyond the classroom.</h2><h3>BUCKEYE CAPITAL INVESTORS</h3><div class="subtitle">Healthcare Sector Analyst · February 2026–present</div><p>One of 20 students selected from 150+ applicants for Ohio State’s investing club, focused on financial accounting, macroeconomics, fundamental analysis, portfolio management, and valuation.</p><h3>BUCKEYE PRIVATE EQUITY AND VENTURE CAPITAL CLUB</h3><div class="subtitle">Analyst · February 2026–present</div><p>One of 25 students selected from 150+ applicants for a multidisciplinary, project-based club focused on private equity and venture capital.</p><h3>INVESTMENT BANKING PATHWAY</h3><div class="subtitle">Member · February 2026–September 2026</div><p>Engaged in a 15-week investment banking training program. As part of the capstone competition, acted as a sell-side advisor for the Intersnack acquisition of Utz, completing a discounted cash flow (DCF) analysis, comparable company analysis, and precedent transactions analysis.</p></article>`,'ACT')}
function fpv(){return heading('FPV','Off the clock')+`<div class="grid">${panel('Flight deck / Personal interests',`<article class="article"><div class="eyebrow">FPV = FIRST-PERSON VIEW</div><h2>I build FPV drones.</h2><div class="subtitle">A hands-on interest in technology.</div><p>Outside my interest in healthcare and finance, I enjoy building first-person-view drones. It’s a chance to work with technology hands-on, assembling something physical that can take flight.</p><h3>WHAT IS FPV?</h3><p>An onboard camera sends a live view to the pilot, often through goggles. That perspective is what gives first-person-view flying its name.</p></article>`,'FPV')}${panel('Beyond work & school',`<article class="article"><div class="eyebrow">OTHER INTERESTS</div><h2>Off the clock.</h2><p>Some of the other things I enjoy and follow:</p><div class="interest-list">${['Fishing','Golfing','Hiking','Longevity','Skiing','Standup Comedy','Technology','Traveling'].map(x=>`<span>${x}</span>`).join('')}</div></article>`,'PERSONAL')}</div>`}
function contact(){return heading('CONTACT','Get in touch')+panel('Contact / Brendan Wilson',`<article class="article"><h2>Let’s connect.</h2><p>Finance student at The Ohio State University, pursuing investment banking.<br>From Boston, Massachusetts.</p><dl class="facts"><dt>Email</dt><dd><a href="mailto:wilson.5645@osu.edu">wilson.5645@osu.edu ↗</a></dd></dl></article>`,'CONTACT')}
function help(){return heading('HELP','Function directory')+panel('Functions',`<article class="article"><h2>Your guide to the terminal.</h2><p>Click any function below, or type its code in the command bar and press Enter. Press <kbd>/</kbd> to focus the command bar and <kbd>Esc</kbd> to close suggestions. Every section is also available through the menus.</p></article><div class="function-list">${Object.entries(functions).filter(([k])=>k!=='HELP').map(([k,v])=>`<button data-view="${k}"><b>${k}</b><span>${v} →</span></button>`).join('')}</div>`,'HELP')}
const views={OV:overview,EXP:experience,EDU:education,ACT:activities,FPV:fpv,CONTACT:contact,HELP:help};
function render(){const key=location.hash.slice(1).toUpperCase()||'OV';current=views[key]?key:'OV';main.innerHTML=views[current]();document.querySelector('#breadcrumb').textContent=functions[current];document.querySelector('#footer-view').textContent=current;document.querySelectorAll('nav [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===current);if(b.dataset.view===current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.title=`Brendan Wilson | ${functions[current]}`;}
function navigate(key){suggestions.hidden=true;document.querySelector('#command-status').hidden=true;if(location.hash==='#'+key)render();else location.hash=key;input.value=''}
document.addEventListener('click',e=>{const job=e.target.closest('[data-job]');if(job){selectedJob=Number(job.dataset.job);navigate('EXP');return}const btn=e.target.closest('[data-view]');if(btn)navigate(btn.dataset.view);if(!e.target.closest('#command-form')&&!e.target.closest('#suggestions'))suggestions.hidden=true});
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();main.focus();main.scrollIntoView()});
const aliases={HOME:'OV',ABOUT:'OV',OVERVIEW:'OV',EXPERIENCE:'EXP',EDUCATION:'EDU',DRONES:'FPV',INTERESTS:'FPV',INVOLVEMENT:'ACT','?':'HELP'};
document.querySelector('#command-form').addEventListener('submit',e=>{e.preventDefault();const value=input.value.trim().toUpperCase().replace(/\s*(<GO>|GO)$/,'').trim();const key=aliases[value]||value;if(functions[key])navigate(key);else{const status=document.querySelector('#command-status');status.textContent='Function not found. Try EXP, EDU, FPV, or HELP.';status.hidden=false}});
function showSuggestions(){const q=input.value.trim().toUpperCase();const matches=Object.entries(functions).filter(([k,v])=>k.includes(q)||v.toUpperCase().includes(q));suggestions.innerHTML=matches.map(([k,v])=>`<button type="button" data-view="${k}">${k}<span>${v}</span></button>`).join('');suggestions.hidden=!matches.length}
input.addEventListener('input',showSuggestions);
input.addEventListener('focus',showSuggestions);
input.addEventListener('click',showSuggestions);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){suggestions.hidden=true;input.blur()}if((e.key==='/'||e.key==='?')&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();if(e.key==='/')input.focus();else navigate('HELP')}});
function tick(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:'America/New_York'}).format(new Date())+' ET'}tick();setInterval(tick,1000);window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();
